### ISSUE TITLE
Test results more consistently

### ISSUE THREAD

**Issue by gurgunday** [RafaelGSS/nodejs-bench-operations#74] opened 2024-05-04 10:44 UTC
https://github.com/nodejs/performance/issues/166#issuecomment-2094019957 suggests that some results are unreliable, if dead code elimination is indeed taking place, we're not getting correct results for the _operations_

We should investigate and find a way to get results that reflect reality

**Comment by RafaelGSS** [comment] 2024-05-04 14:23
dead code elimination is taking place. The idea of this repository is to compare two versions of Node.js performing pretty much the same operation. If version X contains a dead-code elimination (noop) and X+1 doesn't, it should inform. The percentage is irrelevant in microbenchmarking. If we include operations to remove dead code elimination (for instance, `%DoNotOptimize`) it won't give us the reality.

The idea is pretty simple, these operations have changed in Node.js 22 for that specific and unrealistic workload.

**Comment by gurgunday** [comment] 2024-05-04 14:31
I see, yeah I'm not disagreeing, it actually fulfilled its purpose by showing that change

But I wasn't alluding to `%DoNotOptimize`, maybe just small modifications to certain tests so that we can get the actual operations' performance, and v8 can still optimize as much as it can, but doesn't eliminate the whole operation

Small modifications can get us there:

https://github.com/nodejs/performance/issues/166#issuecomment-2094019957

**Comment by RafaelGSS** [comment] 2024-05-04 14:35
I agree! I also suggest moving to another benchmark tool. `tinybench` seems more reliable in my last research.

**Comment by eugene1g** [comment] 2024-05-04 14:54
> The idea of this repository is to compare two versions of Node.js performing pretty much the same operation.

IMO the problem is that when/if dead-code-elimination is at play, the current architecture for benchmarks _does not_ measure the _operation_. If my application does millions of `[].includes()`, the benchmark results say that my code will run  [~10x slower in v22 than in v20](https://github.com/RafaelGSS/nodejs-bench-operations/actions/runs/8946165774/job/24576348629#step:5:50), but in reality there will be no difference at all as my app code doesn't get eliminated. The benchmark results are wrong here because the benchmarking code calling `[].includes()` might get executed all under v20 but runs in v22, but that tells me nothing about how fast that operation would run in v20.

**Comment by RafaelGSS** [comment] 2024-05-09 20:25
Is there a way to see if the code is reaching dead-code elimination? I think it's fair to consider all code to be optimized by V8 (Maglev/Turbofan). We should only make sure that we are not comparing a `noop` with a real operation optimized.

cc: @joyeecheung

**Comment by joyeecheung** [comment] 2024-05-10 09:21
> Is there a way to see if the code is reaching dead-code elimination?

With TurboFan could figure it out by doing `--trace-turbo` and use tools/turbolizer in V8 and look at the graph changes - the elimination is done on basic blocks so it can be difficult to map it back to the original code, depending on how complex your code is. With Maglev I guess some of the `--trace-maglev-*` flags allows you to figure it out too but I've never tried them myself.

To avoid dead code elimination IMO the best way is just to make your benchmarks more sophisticated. If it's too simple and unrealistic you are basically trying to outsmart the optimizing compilers and so that they fail to notice that the code isn't doing anything even though a human can figure out it's not doing anything.

**Comment by RafaelGSS** [comment] 2024-09-27 16:18
Could be fixed by: #256.

**Comment by gurgunday** [comment] 2024-09-27 16:30
Thank you so much!

What do you think of assigning a result of an operation to a global var btw? It seems to fix a lot of the code elimination issues for me

Something like:

```js
let result = "";

const bench = new Bench({ time: 500 });

bench.add("simple HTML formatting", () => {
  result = html`<div>Hello, world!</div>`;
});

bench.add("null and undefined expressions", () => {
  result = html`<p>${null} and ${undefined}</p>`;
});
```

**Comment by RafaelGSS** [comment] 2024-09-27 17:27
It's not guaranteed that it will fix code elimination, other optimizations might take place.[ I was discussing at v8-mail](https://groups.google.com/u/1/g/v8-dev/c/9tHtF2gnL7M) and a feasible (but not realistic way) is to use `%NeverOptimizeFunction` for that. `bench-node` by default, compiles your benchmark using `%NeverOptimizeFunction`. That's why I said: "_could be fixed by ...".  Although, in my tests, it doesn't guarantee a non-optimization as well.

**Comment by RafaelGSS** [comment] 2024-09-30 23:01
I'll analyse the results of https://github.com/RafaelGSS/nodejs-bench-operations/commits/main/?before=b70c29c9c19936e25c7a521682ca52af49390f0f+35&after=b70c29c9c19936e25c7a521682ca52af49390f0f and compare with other tools.

**Closed** 2024-10-08 20:54 UTC
